### PR TITLE
Ggarek feature/129 require other cases

### PR DESCRIPTION
**Pull request by longlho**
try to rebase off master

### CODE REVIEW

**Comment by longlho** [comment]
closes #186

**Comment by longlho** [comment]
@tricoder42 can you give some examples on langs w/o `other`? Unfortunately it is kinda considered the fallback for a lot of i18n vendors

**Comment by tricoder42** [comment]
@longlho As I mentioned in previous [comment](https://github.com/formatjs/intl-messageformat/pull/135#issuecomment-492919221), I'm aware of Polish and Russian.

I also considered `other` as a fallback for a very long time. Then I stumbled upon this issue when users provided `other` prop, but it didn't act like a `other` prop, because their language didn't have it.

**Comment by longlho** [comment]
@tricoder42 do u enforce in lingui or warn?

**Comment by tricoder42** [comment]
I used to enforce `other`, but I dropped that completely.

I'm planning to enforce correct rules based on locale - in the source code based on `sourceLocale` config and in the CLI for each locale. I need to do a research if there's a valid usecase to actually omit a plural rule.

**Comment by longlho** [comment]
OK closing this as won't merge since there's also a workaround which is compile-time validation on source string declaration using `intl-formatmessage-parser`.

**Pull request closed without merging**
