### PR TITLE
throw at compile time if case `other` was not found (see

### PR DESCRIPTION
**Pull request by ggarek**
https://github.com/yahoo/intl-messageformat/issues/129)

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by turadg** [comment]
@okuryu Please merge this. It would have saved me a couple hours today debugging.

**Comment by redonkulus** [comment]
@longlho want to pull this in for v3?

**Comment by longlho** [comment]
sure that works

**Comment by tricoder42** [comment]
Hey guys, I thought that `other` rule should be always present too. However, some languages ([polish](http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#pl), russian, ...) use `other` for decimal numbers. They don't have "fallback" rule, everything is either `one`, `few` or `many.

**Comment by longlho** [comment]
I gotta test this in the field a bit more, primarily bc a lot of vendors don't support anything other than `one` & `other` (e.g Dropbox uses Smartling and they don't, Yahoo's Dragonfly does however). Throwing an error might be too harsh bc the translation string is typically a separate job to poll from vendors.

**Comment by longlho** [comment]
closes in favor of #186

**Pull request closed without merging**
