### PR TITLE
Convert more tests to TS, rm cldr build step

### PR DESCRIPTION
**Pull request by longlho**
- Fix browser tests
- Remove cldr step since we can use `Intl.NumberFormat.supportedLocalesOf()`

Before switching to `Intl.NumberFormat.supportedLocalesOf()`:
```
/m/c/s/intl-messageformat ❯❯❯ npm run benchmark

> intl-messageformat@3.0.0 benchmark /mnt/c/src/intl-messageformat
> ts-node --project tsconfig.all.json tests/benchmark

format_cached_complex_msg x 385,250 ops/sec ±0.62% (90 runs sampled)
format_cached_string_msg x 100,322,485 ops/sec ±6.66% (83 runs sampled)
new_complex_msg_preparsed x 3,762 ops/sec ±4.35% (64 runs sampled)
new_complex_msg x 2,234 ops/sec ±20.57% (86 runs sampled)
new_string_msg x 141,100 ops/sec ±1.61% (91 runs sampled)
```

After switching to `Intl.NumberFormat.supportedLocalesOf()`:
```
/m/c/s/intl-messageformat ❯❯❯ npm run benchmark

> intl-messageformat@3.0.0 benchmark /mnt/c/src/intl-messageformat
> ts-node --project tsconfig.all.json tests/benchmark

format_cached_complex_msg x 390,386 ops/sec ±1.39% (90 runs sampled)
format_cached_string_msg x 109,872,625 ops/sec ±1.34% (87 runs sampled)
new_complex_msg_preparsed x 4,073 ops/sec ±5.68% (73 runs sampled)
new_complex_msg x 2,115 ops/sec ±12.47% (83 runs sampled)
new_string_msg x 53,138 ops/sec ±0.41% (94 runs sampled)
```
Seems like there's no impact on perf. This allows us to dist
less things as well (no need to generate `intl-messageformat-with-locales`)

### CODE REVIEW

**Comment by redonkulus** [comment]
Can you review the readme as well? I believe since you are removing the cldr step that there are some references to locale-data that are invalid now?

**Comment by okuryu** [comment]
yarn.lock may also need to be updated.

**Comment by longlho** [comment]
fixed README & yarn.lock :)

**Comment by redonkulus** [comment]
Looks like the build failed. 

I would say in general, it’s better to wait to squash commits until after a final review. Otherwise, it’s hard for reviewers to see what changed after the initial code review.

**Review by redonkulus — APPROVED** [review]
Changes to readme look good. Merge once build passes.

**Pull request merged**
